IHub-179434 Initial implementation
ov-integrations/kml_import pull request #1
Opened 2021-07-29 17:00 UTC by P4radise

2021-07-29 17:46 UTC, asmoiseenko requested changes

2021-07-29 17:46 UTC, asmoiseenko commented on settings.json
> +    "loginOneVizion": "login",
use access key and secret keys instead of username and password

2021-07-29 17:46 UTC, asmoiseenko commented on kmz_to_kml.py
> +from enum import Enum
rename file to import_kml

2021-07-29 17:46 UTC, asmoiseenko commented on README.md
> +
document currently supported KML struncture

2021-07-29 17:46 UTC, asmoiseenko commented on README.md
> +The integration downloads the KMZ file, extracts data from it and writes them into a CSV file which starts the import of OneVizion
Downloads KMZ file from the specified location, extracts data to CSV file and loads it with the specified OneVizion import.

2021-07-30 08:54 UTC, glebowadim requested changes

2021-07-30 08:54 UTC, glebowadim commented on kmz_to_kml.py
> +        kmz_file = self.download_kmz()
kmz_content?

2021-07-30 08:54 UTC, glebowadim commented on kmz_to_kml.py
> +    def get_csv(self):
Let's separate to 2 classes. 1 class for working with KML(KMZ), 2 class for parsing and create csv file.

2021-07-30 08:54 UTC, glebowadim commented on kmz_to_kml.py
> +            raise Exception(f'Failed extract kml file. Exception [kmz file is stored more than one file]')
... Or less than one file. Is it so critical to receive more than 1 file?

2021-07-30 08:54 UTC, glebowadim commented on kmz_to_kml.py
> +        open(FileNames.KMZ.value, 'wb').write(file)
use ```with```
https://realpython.com/python-with-statement/

2021-07-30 08:54 UTC, glebowadim commented on kmz_to_kml.py
> +                raise Exception(f'Failed parse kml. Exception [Field fire_size not found]')
Lost original exception

2021-08-03 09:52 UTC, P4radise commented on kmz_to_kml.py
> +from enum import Enum
Done

2021-08-03 09:52 UTC, P4radise commented on settings.json
> +    "loginOneVizion": "login",
Done

2021-08-03 09:52 UTC, P4radise commented on README.md
> +The integration downloads the KMZ file, extracts data from it and writes them into a CSV file which starts the import of OneVizion
Done

2021-08-03 09:53 UTC, P4radise commented on integration_log.py
> +class IntegrationLog(object):
Done

2021-08-03 09:53 UTC, P4radise commented on kmz_to_kml.py
> +        return f'Fires-{current_date}'
I found the date in the KML file, so now I take it from there and the constant is no longer needed

2021-08-03 09:54 UTC, P4radise commented on kmz_to_kml.py
> +    def start_import(self, import_id, file_name):
Done

2021-08-03 09:54 UTC, P4radise commented on kmz_to_kml.py
> +class FileNames(Enum):
Done

2021-08-03 09:54 UTC, P4radise commented on kmz_to_kml.py
> +        try:
Done

2021-08-03 09:54 UTC, P4radise commented on kmz_to_kml.py
> +        kmz_file = self.download_kmz()
Done

2021-08-03 09:54 UTC, P4radise commented on kmz_to_kml.py
> +    def get_csv(self):
Done

2021-08-03 09:54 UTC, P4radise commented on kmz_to_kml.py
> +        open(FileNames.KMZ.value, 'wb').write(file)
Done

2021-08-03 09:55 UTC, P4radise commented on kmz_to_kml.py
> +            raise Exception(f'Failed extract kml file. Exception [kmz file is stored more than one file]')
I added a loop, now the files will be searched, if several kml files are found or less than one, an Exception will be called

2021-08-03 09:57 UTC, P4radise commented on kmz_to_kml.py
> +                raise Exception(f'Failed parse kml. Exception [Field fire_size not found]')
The original error would say that you cannot call the group function for an empty value, which means that no fire_size value was found.
If it is necessary, I can split this line and add some conditions.

2021-08-03 11:00 UTC, asmoiseenko commented on kmz_to_kml.py
> +                raise Exception(f'Failed parse kml. Exception [Field fire_size not found]')
you know all exceptions which can be thrown? Never swallow original exception

2021-08-03 11:17 UTC, asmoiseenko requested changes
Also, add XML with a sample OneVizion config, so we can deploy and test this integration somewhere

2021-08-03 11:17 UTC, asmoiseenko commented on import_kml.py
> +    KMZ = 'fires.kmz'
why fires? This is kml_import integration, it is not necessarily deal with fires related data. If you need to create temp files, use a different approach.

2021-08-03 11:17 UTC, asmoiseenko commented on import_kml.py
> +        answer = requests.get(url)
rename to `response`. The answer is for the question.

2021-08-03 11:17 UTC, asmoiseenko commented on import_kml.py
> +                    raise Exception(f'Failed extract kml file. Exception [kmz file stores more than one kml file]')
I see nothing about this limitation in the readme. Also, you didn't address the following comment https://github.com/ov-integrations/kml_import/pull/1#discussion_r679360947

2021-08-03 11:17 UTC, asmoiseenko commented on import_kml.py
> +            raise Exception(f'Failed download kmz. Exception [{answer.text}]')
Why don`t you have a common global exception handling block where you will log errors?

2021-08-03 11:17 UTC, asmoiseenko commented on import_kml.py
> +            parse_list.append({CSVHeader.REG_ID.value:registration_id, CSVHeader.NAME.value:name, CSVHeader.DESCRIPTION.value:description, \
You have to document CSV file structure in the readme.

2021-08-03 11:17 UTC, asmoiseenko commented on start_integration.py
> +if re.search('https', settings_data['urlOneVizion']) is None:
make your regexp work both with and without "s" in the URL protocol and remove this condition

2021-08-03 12:08 UTC, P4radise commented on import_kml.py
> +    KMZ = 'fires.kmz'
Okay, I will replace the file names, but in any case the parser is designed for a specific kml file, so many variables use the name fire

2021-08-03 12:16 UTC, P4radise commented on import_kml.py
> +                    raise Exception(f'Failed extract kml file. Exception [kmz file stores more than one kml file]')
Okay, I'll add the information to the readme.
I missed that comment. But I don't understand it. Do I need to add an example of a kml file structure that is supported by this integration?

2021-08-03 16:28 UTC, P4radise commented on start_integration.py
> +if re.search('https', settings_data['urlOneVizion']) is None:
Done

2021-08-03 16:28 UTC, P4radise commented on import_kml.py
> +            raise Exception(f'Failed download kmz. Exception [{answer.text}]')
Done

2021-08-03 16:29 UTC, P4radise commented on import_kml.py
> +                    raise Exception(f'Failed extract kml file. Exception [kmz file stores more than one kml file]')
I added the kml structure to the readme

2021-08-03 16:29 UTC, P4radise commented on import_kml.py
> +        answer = requests.get(url)
Done

2021-08-03 16:29 UTC, P4radise commented on kmz_to_kml.py
> +                raise Exception(f'Failed parse kml. Exception [Field fire_size not found]')
Got it, fixed it

2021-08-03 17:16 UTC, P4radise commented
> Also, add XML with a sample OneVizion config, so we can deploy and test this integration somewhere

Done

2021-08-04 02:08 UTC, glebowadim requested changes

2021-08-04 02:08 UTC, glebowadim commented on kmz_to_kml.py
> +                raise Exception(f'Failed parse kml. Exception [Field fire_size not found]')
Oh, it's OK. Sorry. 
"Exception chaining happens automatically when an exception is raised inside an except or finally section."

2021-08-04 04:57 UTC, asmoiseenko commented on kmz_to_kml.py
> +                raise Exception(f'Failed parse kml. Exception [Field fire_size not found]')
you have to **handle**, **not collect** exceptions in a single place

2021-08-04 05:03 UTC, P4radise commented on import_kml.py
> +            raise Exception(e)
I deleted it

2021-08-04 05:03 UTC, P4radise commented on import_kml.py
> +    KMZ = 'file.kmz'
Done

2021-08-04 05:03 UTC, P4radise commented on import_kml.py
> +        except Exception as e:
I deleted it

2021-08-04 05:04 UTC, P4radise commented on import_kml.py
> +    def get(self, kmz_file, kml_file):
Done

2021-08-04 05:05 UTC, P4radise commented on kmz_to_kml.py
> +                raise Exception(f'Failed parse kml. Exception [Field fire_size not found]')
I have already handled these exceptions by adding conditions

2021-08-04 05:05 UTC, asmoiseenko commented on import_kml.py
> +    KMZ = 'fires.kmz'
think about how you could make our code more generic. You just parse the placemark description and save values from it to the dedicated field. You may allow users to specify regexp patterns to use for values extraction in the integration config, see how it was done in the ov-monitoring integration:

settings.json
```json
{
   "extractPlacemarkDescriptionValues": [
        {"fireSize": "\d+\sacres|\d+acres"}, 
        {"date":"\d+-\w+-\d+"}
    ]

}
```

2021-08-04 05:05 UTC, P4radise commented on import_kml.py
> +class IntegrationException:
Done

2021-08-04 07:05 UTC, P4radise commented on import_kml.py
> +    KMZ = 'fires.kmz'
Okay, I see your point, but let's save that change for the next Issue.
Now let's run this integration for a particular kml structure.

2021-08-05 02:26 UTC, glebowadim requested changes

2021-08-05 02:26 UTC, glebowadim commented on start_integration.py
> +integration.start_integration()
Move exception handling here

2021-08-05 02:26 UTC, glebowadim commented on import_kml.py
> +        if date is None:
```  
if date is None:
    raise Exception(f'Failed parse KML. Exception [Date for registration_id not found]')

registration_id = f'Fires-{datetime.strptime(date.group(), "%d-%b-%Y").strftime(...
```

2021-08-05 02:26 UTC, glebowadim commented on import_kml.py
> +        if kml_filename_to_extract is None:
```  
if kml_filename_to_extract is None:
    raise Exception(f'Failed extract KML file. Exception [KML file not found in KMZ]')
kml.extract(kml_filename_to_extract)
os.rename(kml_filename_to_extract, kml_filename)
self.integration_log.add(LogLevel.INFO, 'KML file extracted')
```

2021-08-05 02:26 UTC, glebowadim commented on import_kml.py
> +            if import_id is None:
```        
  if import_id is None:
      raise Exception(f'Import \"{self.import_name}\" not found')
  self.integration_log.add(LogLevel.INFO, f'Import \"{self.import_name}\" founded')
```

2021-08-05 04:19 UTC, P4radise commented on import_kml.py
> +            if import_id is None:
Done

2021-08-05 04:19 UTC, P4radise commented on import_kml.py
> +        if kml_filename_to_extract is None:
Done

2021-08-05 04:19 UTC, P4radise commented on import_kml.py
> +        if date is None:
Done

2021-08-05 04:19 UTC, P4radise commented on start_integration.py
> +integration.start_integration()
Done

2021-08-05 04:35 UTC, glebowadim approved these changes

2021-08-05 04:55 UTC, merged