IHub-182879 Move the filling of some fields to the rule
ov-integrations/kml_import pull request #2
Opened 2021-09-28 09:14 UTC by P4radise

2021-09-28 14:19 UTC, glebowadim approved these changes

2021-09-29 04:25 UTC, asmoiseenko requested changes

2021-09-29 04:25 UTC, asmoiseenko commented on import_kml.py
>                  raise Exception(f'Failed parse KML. Exception [Field description not found]')
what is the problem to run with an empty description?

2021-09-29 04:33 UTC, P4radise commented on import_kml.py
>                  raise Exception(f'Failed parse KML. Exception [Field description not found]')
The problem here is not that the description may be empty, but that this field may not be found. But this field will have some data in any case, if it is found in kml.

2021-09-29 04:33 UTC, P4radise commented on import_kml.py
>                  raise Exception(f'Failed parse KML. Exception [Field description not found]')
The problem here is not that the description may be empty, but that this field may not be found. But this field will have some data in any case, if it is found in kml.

2021-09-29 05:31 UTC, asmoiseenko requested changes

2021-09-29 05:31 UTC, asmoiseenko commented on import_kml.py
> +                self.integration_log.add(LogLevel.WARNING, f'Failed parse KML. Exception [Field description not found for {name}]')
correct error message to something more relevant: "Description field is not found for XXX, it will be skipped"

2021-09-29 05:34 UTC, P4radise commented on import_kml.py
> +                self.integration_log.add(LogLevel.WARNING, f'Failed parse KML. Exception [Field description not found for {name}]')
Done

2021-09-29 05:37 UTC, asmoiseenko approved these changes

2021-09-29 05:37 UTC, merged