IHub-214263 Add automatic installation of dependencies
ov-integrations/kml_import pull request #3
Opened 2022-04-28 04:12 UTC by P4radise

2022-05-02 14:28 UTC, glebowadim requested changes

2022-05-02 14:28 UTC, glebowadim commented on settings.json
> +    "commandStart": "python3 module_settings.py"
I think it is a constant. Why is this needed in settings.json?

2022-05-02 14:28 UTC, glebowadim commented on start_module.py
> +os.system(settings_data['commandStart'])
use ```subprocess.run()``` instead

2022-05-02 14:28 UTC, glebowadim commented on settings.json
> +    "commandStart": "python3 module_settings.py"
And I'm not sure about the name. Maybe ```start_module_without_installing_dependencies.py``` ?

2022-05-04 04:26 UTC, P4radise commented on settings.json
> +    "commandStart": "python3 module_settings.py"
Generally yes, it should be a constant, because usually we run the same file that already runs the module.
But in this module - https://github.com/ov-integrations/sftp_to_onevizion - there are 2 files that can run, so I put it in the settings file.
Again, this is most likely not a properly made module, and it might be worth making changes within it, then we can leave it as a constant.

2022-05-04 05:04 UTC, P4radise commented on start_module.py
> +os.system(settings_data['commandStart'])
Done

2022-05-05 08:39 UTC, glebowadim commented on settings.json
> +    "commandStart": "python3 module_settings.py"
@asmoiseenko 
What do you think about this name ```module_settings.py```?

2022-07-11 11:47 UTC, asmoiseenko requested changes
We decide to exit with a warning message if new libraries were installed. The message should be: "Some required dependent libraries were installed. Module execution has to be terminated now to use installed libraries on the next scheduled launch"

2022-07-28 08:54 UTC, P4radise commented
> We decide to exit with a warning message if new libraries were installed. The message should be: "Some required dependent libraries were installed. Module execution has to be terminated now to use installed libraries on the next scheduled launch"

Now if the libraries were installed for the first time and their import causes an error we will see this error log:

```
  WARNING: The script jsonschema is installed in '/home/u_1000303/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Traceback (most recent call last):
  File "start_module.py", line 7, in <module>
    from jsonschema import validate
ModuleNotFoundError: No module named 'jsonschema'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "start_module.py", line 13, in <module>
    raise Exception(f'Some required dependent libraries were installed. Module execution has to be terminated now to use installed libraries on the next scheduled launch.\n{str(e)}')
Exception: Some required dependent libraries were installed. Module execution has to be terminated now to use installed libraries on the next scheduled launch.
No module named 'jsonschema'
```

Or there is another option, we can use the SystemExit and then we will see this message:
```
  WARNING: The script jsonschema is installed in '/home/u_1000304/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Some required dependent libraries were installed. Module execution has to be terminated now to use installed libraries on the next scheduled launch.
No module named 'jsonschema'
```

Which option would be preferable?

2022-07-28 09:35 UTC, asmoiseenko requested changes

2022-07-28 09:35 UTC, asmoiseenko commented on start_module.py
> +    raise Exception(f'Some required dependent libraries were installed. Module execution has to be terminated now to use installed libraries on the next scheduled launch.\n{str(e)}')
I do not think you are catching right errors here. Import errors may be not related to dependencies installations at all. I proposed to handle errors from `subprocess.check_call` https://docs.python.org/3/library/subprocess.html#subprocess.check_call

2022-08-17 15:09 UTC, P4radise commented on start_module.py
> +    raise Exception(f'Some required dependent libraries were installed. Module execution has to be terminated now to use installed libraries on the next scheduled launch.\n{str(e)}')
I don't think there can be any errors from subprocess.check_call related to the libraries not being able to be imported.

If there will be any problems importing libraries, it will only be the first time after they have been installed. Well, if there are any import errors later on, we will see it in the callstack, albeit with the same message.

Again, I don't know of any problems with importing libraries other than the fact that they are not installed.

2022-08-25 09:32 UTC, asmoiseenko requested changes

2022-08-25 09:32 UTC, asmoiseenko commented on start_module.py
> +    raise Exception(f'Some required dependent libraries were installed. Module execution has to be terminated now to use installed libraries on the next scheduled launch.\n{str(e)}')
I propose to check output of the `subprocess.check_call` and if any libraries were installed rise an error:
```python
subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-r', 'python_dependencies.txt'])
#check output

if is_installed_dependencies:
    raise Exception(f'Some required dependent libraries were installed. Module execution has to be terminated now to use installed libraries on the next scheduled launch.\n{str(e)}')

from jsonschema import validate
from import_kml import Integration, KML, CSV, Import
...
```

2022-08-25 10:21 UTC, P4radise commented on start_module.py
> +    raise Exception(f'Some required dependent libraries were installed. Module execution has to be terminated now to use installed libraries on the next scheduled launch.\n{str(e)}')
When installing a new library (or when installing a new version of a library) we may see the following text:
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: jsonschema==4.4.0 in /Users/iemelyanov/Library/Python/3.8/lib/python/site-packages (from -r python_dependencies.txt (line 1)) (4.4.0)
Collecting onevizion==1.0.35
  Using cached onevizion-1.0.35-py3-none-any.whl
Requirement already satisfied: beautifulsoup4==4.11.1 in /Users/iemelyanov/Library/Python/3.8/lib/python/site-packages (from -r python_dependencies.txt (line 3)) (4.11.1)
Requirement already satisfied: lxml==4.8.0 in /Users/iemelyanov/Library/Python/3.8/lib/python/site-packages (from -r python_dependencies.txt (line 4)) (4.8.0)
Requirement already satisfied: requests==2.27.1 in /Users/iemelyanov/Library/Python/3.8/lib/python/site-packages (from -r python_dependencies.txt (line 5)) (2.27.1)
...
...
Installing collected packages: onevizion
Successfully installed onevizion-1.0.35
```

Respectively, we can monitor "Successfully installed", if it is in the output, we will give an error and terminate the Module.

2022-08-25 11:41 UTC, asmoiseenko approved these changes

2022-08-26 04:01 UTC, glebowadim requested changes

2022-08-26 04:01 UTC, glebowadim commented on start_module.py
> +    raise Exception('Some required dependent libraries were installed. Module execution has to be terminated now to use installed libraries on the next scheduled launch.')
![image](https://user-images.githubusercontent.com/7280762/186816109-2394c42e-01e2-4629-9d4c-0e7b1ef4777b.png)

2022-08-26 07:00 UTC, P4radise commented on start_module.py
> +    raise Exception('Some required dependent libraries were installed. Module execution has to be terminated now to use installed libraries on the next scheduled launch.')
Done

2022-08-26 07:08 UTC, glebowadim approved these changes

2022-08-26 09:10 UTC, asmoiseenko requested changes

2022-08-26 09:10 UTC, asmoiseenko commented on start_module.py
> +installed_dependencies = subprocess.check_output(
btw, what about the following recommendation:
[Code needing to capture stdout or stderr should use run() instead](https://docs.python.org/3/library/subprocess.html#older-high-level-api)

https://docs.python.org/3/library/subprocess.html#subprocess.run

![image](https://user-images.githubusercontent.com/13415820/186869698-6d915f6a-d43c-49a6-bf9d-85a0cde3b8e8.png)

2022-08-26 09:22 UTC, P4radise commented on start_module.py
> +installed_dependencies = subprocess.check_output(
What we use is the same as using run with additional parameters
```
This is equivalent to:
run(..., check=True, stdout=PIPE).stdout
```
https://docs.python.org/3/library/subprocess.html#subprocess.check_output

2022-08-26 09:32 UTC, asmoiseenko commented on start_module.py
> +installed_dependencies = subprocess.check_output(
but looks `subprocess.check_output` is obsolete, and run is preferred way to do things in a new code
`Prior to Python 3.5, these three functions comprised the high level API to subprocess. You can now use [run()](https://docs.python.org/3/library/subprocess.html#subprocess.run) in many cases, but lots of existing code calls these functions.`

2022-08-26 09:32 UTC, asmoiseenko approved these changes

2022-08-26 09:43 UTC, merged